services:
  db:
    image: arashlml/my-pgvector-image:latest
    environment:
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_DB=langchain
    ports:
      - "6024:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    entrypoint: ["/bin/sh", "-c", "docker-entrypoint.sh postgres && psql -U langchain -d langchain -c 'CREATE EXTENSION IF NOT EXISTS vector;'"]
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://langchain:langchain@db:5432/langchain

    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./chatbot:/app/chatbot

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:8501"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app-network
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull nomic-embed-text && wait"]
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge